#开发配置
spring:
  profiles: 
    active: dev
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#配置mybatis的扫描的包的文件的入口
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath*:mybatis/mapper/*.xml

#配置统一前缀，然后要干掉前缀的
zuul:
  prefix: /api
  SendErrorFilter:
    error:
      disable: true
#ribbon
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
feign:
  authService: framework-auth