#端口号设置
server:
  port: 9000
  
#数据库连接配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.18.44.111:3306/adyl_logistics_loops?characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false
    username: app
    password: "appserver123!@#"
